name: CI Build, Test, Coverage & Pages

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-test-coverage:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj', '**/packages.config') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
            
      - name: Install MonoGame Content Builder
        run: dotnet tool install --global dotnet-mgcb --version 3.8.3
        
      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Restore dependencies
        run: dotnet restore

      - name: Add global tools to PATH
        run: echo "%USERPROFILE%\.dotnet\tools" >> $Env:GITHUB_PATH

      - name: Build library
        run: dotnet build SearchitLibrary/SearchitLibrary.csproj --no-restore --configuration Release
        
      - name: Build executable
        run: dotnet build SearchitBreakher/SearchitBreakher.csproj --no-restore --configuration Release /p:MonoGameContentBuilderVerbose=true
      - name: Build tests
        run: dotnet build SearchitTest/SearchitTest.csproj --no-restore --configuration Release

      - name: Run unit tests with coverage
        run: dotnet test SearchitTest/SearchitTest.csproj --no-build --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:CoverletOutput=TestResults/coverage/


      - name: Generate HTML coverage report
        run: |
          reportgenerator \
            -reports:TestResults/coverage/coverage.opencover.xml \
            -targetdir:coverage-report \
            -reporttypes:Html

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: TestResults/coverage/coverage.opencover.xml

      - name: Upload coverage report for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: coverage-report
